name: Arduino CI/CD for ESP32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: '0.19.2'

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32 ./ESP32-Hard-Fault-Tests/ESP32_Hard_Fault_Tests.ino

    - name: Run Tests
      run: arduino-cli test --fqbn esp32:esp32:esp32 ./ESP32-Hard-Fault-Tests/ESP32_Hard_Fault_Tests.ino
